security.protocol=SSL
ssl.key.password=confluent
ssl.keystore.location=/home/ubuntu/Ansible/Schema/certs/kafka-0.keystore.jks
ssl.keystore.password=confluent
ssl.truststore.location=/home/ubuntu/Ansible/Schema/certs/kafka-0.truststore.jks
ssl.truststore.password=confluent
