---
- name: Kafka Connector Credentials Secrets Deployment
  hosts: kafka_connect
  gather_facts: false
  tags: kafka_connect
  environment: "{{ proxy_env }}"
  vars:
     connector_credentials_secrets_file: /opt/confluent/secrets/credentials.properties
  tasks:

    - import_role:
        name: variables

#we can pull the api_key from AWS secrets       
    - name: Set API Key from AWS
      set_fact:
        custom_facts:
          api_key: "xxxxx"
          api_secret: "yyyyy"

    - name: Create Security Properties File
      file:
        path: "{{ connector_credentials_secrets_file  }}"
        owner: "{{kafka_connect_user}}"
        group: "{{kafka_connect_group}}"
        state: touch

    - debug:
        msg: "{{ custom_facts | dict2items }}"

    - name: Write variables to a file
      shell: |
             echo "{{item.key|trim}}={{item.value|trim}}">>"{{ connector_credentials_secrets_file  }}"
      loop: "{{ custom_facts | dict2items }}"

    - name: Create Encrypt Properties List
      set_fact:
         final_encrypt_properties: "{{ custom_facts | dict2items | map(attribute='key') | list }}"

    - name: Encrypt Properties
      shell: |
       {{ confluent_cli_path }} secret file encrypt --local-secrets-file {{ secrets_protection_security_file }} \
         --remote-secrets-file {{ secrets_protection_security_file }} \
         --config-file {{ connector_credentials_secrets_file }} \
         --config "{{ final_encrypt_properties  | join (',') }}"
      environment:
        CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
      changed_when: true
