bootstrap.servers=kafka-0.rrchakdc1.ans.test.io:9097
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=kafka
security.protocol=SASL_SSL
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required \
    useKeyTab=true \
    storeKey=true \
    keyTab="/home/ubuntu/Ansible/Schema/kerberos/keytabs/_data/kafka-client.keytab" \
    useTicketCache=false \
    principal="kafka_producer@TEST.CONFLUENT.IO";
ssl.key.password=confluent
ssl.keystore.location=/home/ubuntu/Ansible/Schema/certs/kafka-0.keystore.jks
ssl.keystore.password=confluent
ssl.truststore.location=/home/ubuntu/Ansible/Schema/certs/kafka-0.truststore.jks
ssl.truststore.password=confluent

