bootstrap.servers=kafka-0.rrchakdc2.ans.test.io:9095
#security.protocol=SSL
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="rang" \
  password="rang-secret";
ssl.truststore.location=/home/ubuntu/Ansible/Schema/certs/client.truststore.jks
ssl.truststore.password=confluent
ssl.keystore.location=/home/ubuntu/Ansible/Schema/certs/client.keystore.jks
ssl.keystore.password=confluent
ssl.key.password=confluent
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
schema.registry.url=https://kafka-0.rrchakdc2.ans.test.io:8081
basic.auth.credentials.source=USER_INFO
schema.registry.basic.auth.user.info=rang:rang-secret
schema.registry.ssl.truststore.location=/home/ubuntu/Ansible/Schema/certs/client.truststore.jks
schema.registry.ssl.truststore.password=confluent
schema.registry.ssl.truststore.type=JKS
schema.registry.ssl.keystore.location=/home/ubuntu/Ansible/Schema/certs/client.keystore.jks
schema.registry.ssl.keystore.password=confluent
schema.registry.ssl.key.password=confluent
schema.registry.ssl.keystore.type=JKS
schema.registry.ssl.endpoint.identification.algorithm=HTTPS